export const GET_QUOTE_INITIATED = 'GET_QUOTE_INITIATED';
export const GET_QUOTE_SUCCESS = 'GET_QUOTE_SUCCESS';
export const GET_QUOTE_FAILURE = 'GET_QUOTE_FAILURE';
export const SET_LOADING = 'SET_LOADING';

export const ADD_FAVOURITE_INITIATED = 'ADD_FAVOURITE_INITIATED';
export const ADD_FAVOURITE_SUCCESS = 'ADD_FAVOURITE_SUCCESS';
export const ADD_FAVOURITE_FAILURE = 'ADD_FAVOURITE_FAILURE';

export const GET_FAVOURITE_INITIATED = 'GET_FAVOURITE_INITIATED';
export const GET_FAVOURITE_SUCCESS = 'GET_FAVOURITE_SUCCESS';
export const GET_FAVOURITE_FAILURE = 'GET_FAVOURITE_FAILURE';

export const DELETE_FAVOURITE_INITIATED = 'DELETE_FAVOURITE_INITIATED';
export const DELETE_FAVOURITE_SUCCESS = 'DELETE_FAVOURITE_SUCCESS';
export const DELETE_FAVOURITE_FAILURE = 'DELETE_FAVOURITE_FAILURE';

export const SEARCH_INITIATED = 'SEARCH_INITIATED';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';